"""The live market: a simulated session that actually moves.

Until now the market was a pile of daily bars ending at the last generated day,
which is fine for backtests and useless for watching. This advances a simulated
clock in real time, generates intraday prices from the last close, and rolls each
finished session into a new daily bar - so history keeps growing and the agent
always has a fresh session to trade.

Time is compressed: one real second is `MINUTES_PER_SECOND` simulated minutes, so
a 390-minute session plays out in a few minutes of watching. The prices are
generated by the same volatility parameters the instrument was created with, so a
utility crawls and a small-cap tech name lurches, exactly as in the daily data.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from decimal import Decimal

import numpy as np
from redis.asyncio import Redis
from sqlalchemy import select
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.logging import get_logger
from app.market.calendar import next_trading_day, session_close_utc
from app.models import Bar, Instrument

log = get_logger(__name__)

# --- the compressed clock ----------------------------------------------------
MINUTES_PER_SECOND = 3.0        # one real second is three simulated minutes
SESSION_MINUTES = 390.0         # a normal 09:30-16:00 session
TICK_SECONDS = 2.0              # how often prices are regenerated

QUOTE_KEY = "quote:{symbol}"
CHANNEL = "market:quotes"
CLOCK_KEY = "market:clock"

TRADING_DAYS = 252


@dataclass
class LiveQuote:
    symbol: str
    last: float
    open: float
    high: float
    low: float
    change_pct: float
    volume: int
    ts: str

    def to_dict(self) -> dict:
        return {
            "symbol": self.symbol,
            "last": round(self.last, 4),
            "open": round(self.open, 4),
            "high": round(self.high, 4),
            "low": round(self.low, 4),
            "change_pct": round(self.change_pct, 3),
            "volume": self.volume,
            "ts": self.ts,
        }


@dataclass
class SessionState:
    """One simulated trading session in progress."""

    day: datetime
    minutes_elapsed: float
    previous_close: dict[str, float]
    open_price: dict[str, float]
    last: dict[str, float]
    high: dict[str, float]
    low: dict[str, float]
    volume: dict[str, int]

    @property
    def finished(self) -> bool:
        return self.minutes_elapsed >= SESSION_MINUTES

    @property
    def progress(self) -> float:
        return min(1.0, self.minutes_elapsed / SESSION_MINUTES)


async def latest_closes(session: AsyncSession) -> tuple[datetime | None, dict[str, dict]]:
    """The most recent close per symbol, with the parameters needed to move it."""
    newest = await session.scalar(
        select(Bar.ts).where(Bar.timeframe == "1d").order_by(Bar.ts.desc()).limit(1)
    )
    if newest is None:
        return None, {}

    rows = (
        await session.execute(
            select(
                Instrument.symbol, Instrument.annual_vol, Instrument.shares_outstanding,
                Bar.close, Bar.volume,
            )
            .join(Bar, Bar.instrument_id == Instrument.id)
            .where(Bar.ts == newest, Bar.timeframe == "1d", Instrument.is_tradable.is_(True))
        )
    ).all()

    return newest, {
        symbol: {
            "close": float(close),
            "annual_vol": float(vol or 0.30),
            "avg_volume": int(volume or 1_000_000),
            "shares": int(shares or 1_000_000),
        }
        for symbol, vol, shares, close, volume in rows
    }


def start_session(day: datetime, universe: dict[str, dict], seed: int) -> SessionState:
    """Open a new session with a modest overnight gap on every name."""
    rng = np.random.default_rng(seed)
    previous = {s: d["close"] for s, d in universe.items()}
    opens: dict[str, float] = {}

    for symbol, data in universe.items():
        daily_vol = data["annual_vol"] / np.sqrt(TRADING_DAYS)
        gap = float(rng.normal(0, daily_vol * 0.35))
        opens[symbol] = max(0.35, previous[symbol] * float(np.exp(gap)))

    return SessionState(
        day=day,
        minutes_elapsed=0.0,
        previous_close=previous,
        open_price=opens,
        last=dict(opens),
        high=dict(opens),
        low=dict(opens),
        volume=dict.fromkeys(universe, 0),
    )


def advance(
    state: SessionState, universe: dict[str, dict], minutes: float, rng: np.random.Generator
) -> list[LiveQuote]:
    """Move every price forward by `minutes` of simulated time."""
    quotes: list[LiveQuote] = []
    fraction = minutes / SESSION_MINUTES

    for symbol, data in universe.items():
        daily_vol = data["annual_vol"] / np.sqrt(TRADING_DAYS)
        step_vol = daily_vol * np.sqrt(fraction)

        # A touch of pull back towards the open keeps a compressed session from
        # wandering to an implausible place by the close.
        drift_home = -0.06 * np.log(state.last[symbol] / state.open_price[symbol]) * fraction
        move = float(rng.normal(drift_home, step_vol))

        price = max(0.35, state.last[symbol] * float(np.exp(move)))
        state.last[symbol] = price
        state.high[symbol] = max(state.high[symbol], price)
        state.low[symbol] = min(state.low[symbol], price)

        # Volume accrues through the session, heavier when the price is moving.
        per_minute = data["avg_volume"] / SESSION_MINUTES
        intensity = 0.6 + 2.2 * min(3.0, abs(move) / max(step_vol, 1e-9))
        state.volume[symbol] += int(per_minute * minutes * intensity)

        previous = state.previous_close[symbol]
        quotes.append(
            LiveQuote(
                symbol=symbol,
                last=price,
                open=state.open_price[symbol],
                high=state.high[symbol],
                low=state.low[symbol],
                change_pct=(price / previous - 1) * 100 if previous else 0.0,
                volume=state.volume[symbol],
                ts=datetime.now(UTC).isoformat(),
            )
        )

    state.minutes_elapsed += minutes
    return quotes


async def publish(redis: Redis, quotes: list[LiveQuote], state: SessionState) -> None:
    """Write the hot quote for each symbol and fan the batch out to subscribers."""
    pipe = redis.pipeline()
    for quote in quotes:
        pipe.hset(
            QUOTE_KEY.format(symbol=quote.symbol),
            mapping={
                "last": str(round(quote.last, 4)),
                "change_pct": str(round(quote.change_pct, 3)),
                "ts": quote.ts,
            },
        )
    pipe.set(
        CLOCK_KEY,
        json.dumps({
            "session_date": state.day.date().isoformat(),
            "minutes_elapsed": round(state.minutes_elapsed, 1),
            "progress": round(state.progress, 4),
            "open": not state.finished,
        }),
    )
    await pipe.execute()

    await redis.publish(
        CHANNEL,
        json.dumps({
            "type": "quotes",
            "session_date": state.day.date().isoformat(),
            "progress": round(state.progress, 4),
            "quotes": [q.to_dict() for q in quotes],
        }),
    )


async def close_session(
    session: AsyncSession, state: SessionState, universe: dict[str, dict]
) -> int:
    """Write the finished session as a daily bar for every symbol.

    This is what keeps the simulation going rather than replaying one frozen day:
    history grows, and tomorrow the agent has a genuinely new session to trade.
    """
    ids = dict(
        (
            await session.execute(select(Instrument.symbol, Instrument.id))
        ).all()
    )
    ts = session_close_utc(state.day.date())

    rows = [
        {
            "instrument_id": ids[symbol],
            "ts": ts,
            "timeframe": "1d",
            "open": Decimal(str(round(state.open_price[symbol], 4))),
            "high": Decimal(str(round(state.high[symbol], 4))),
            "low": Decimal(str(round(state.low[symbol], 4))),
            "close": Decimal(str(round(state.last[symbol], 4))),
            "volume": max(1000, state.volume[symbol]),
        }
        for symbol in universe
        if symbol in ids
    ]
    if not rows:
        return 0

    stmt = insert(Bar).values(rows)
    stmt = stmt.on_conflict_do_update(
        index_elements=[Bar.instrument_id, Bar.ts, Bar.timeframe],
        set_={c: stmt.excluded[c] for c in ("open", "high", "low", "close", "volume")},
    )
    await session.execute(stmt)
    await session.flush()

    # The new closes become tomorrow's reference prices.
    for symbol in universe:
        universe[symbol]["close"] = state.last[symbol]

    log.info("session_closed", day=str(state.day.date()), bars=len(rows))
    return len(rows)


def next_session_day(day: datetime) -> datetime:
    return datetime.combine(
        next_trading_day(day.date()), datetime.min.time(), tzinfo=UTC
    ) + timedelta(hours=14)


__all__ = [
    "CHANNEL",
    "CLOCK_KEY",
    "MINUTES_PER_SECOND",
    "QUOTE_KEY",
    "SESSION_MINUTES",
    "TICK_SECONDS",
    "LiveQuote",
    "SessionState",
    "advance",
    "close_session",
    "latest_closes",
    "next_session_day",
    "publish",
    "start_session",
]
